### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by bondarenkoi07** [PoorMercymain/REST-API-work-duration-counter#1]
https://github.com/PoorMercymain/REST-API-work-duration-counter/blob/3894df68585da6d1ff8e2edb718870f707b86eb9/internal/repository/connect.go#L18 сюда передавать строку `DSN`, либо сами параметры, либо идти в `env` через `os.Getenv("foobar")`

**Comment by bondarenkoi07** [comment]
https://github.com/PoorMercymain/REST-API-work-duration-counter/blob/3894df68585da6d1ff8e2edb718870f707b86eb9/internal/repository/connect.go#L21 тут соответственно параметры передавать.

**Comment by bondarenkoi07** [comment]
https://github.com/PoorMercymain/REST-API-work-duration-counter/blob/3894df68585da6d1ff8e2edb718870f707b86eb9/internal/repository/connect.go#L12 зачем хранить компоненты dsn? Ты используешь эти параметры один раз, лучше храни тут *pgx.Conn.

**Comment by bondarenkoi07** [comment]
https://github.com/PoorMercymain/REST-API-work-duration-counter/blob/3894df68585da6d1ff8e2edb718870f707b86eb9/internal/repository/connect.go#L35 Этот метод убрать, а создание *pgx.Conn перенести в конструктор, ну и переименовать `dsnBuilder -> dbconn`. Создание подключения к бд по дсн происходит один раз, в логику не входит, зачем целый объект под это отдавать. А  *pgx.Conn в двух репозиториях будем использовать.

**Comment by PoorMercymain** [comment]
Спасибо за ревью.
